export const ROUTES = {
  home: "/",
  sobre: "/sobre",
  contacto: "/contacto",
  eventos: "/eventos",
  evento: (slug: string) => `/eventos/${slug}`,
  eventoEntradas: (slug: string) => `/eventos/${slug}/entradas`,
  eventoListaPrecios: (slug: string) => `/eventos/${slug}/lista-precios`,
  comunidad: "/comunidad",
  login: "/login",
  miCuenta: "/mi-cuenta",
  miCuentaEntradas: "/mi-cuenta/entradas",
  admin: "/admin",
  adminEventos: "/admin/eventos",
  adminEventosCrear: "/admin/eventos/crear",
  adminEvento: (id: string) => `/admin/eventos/${id}`,
  adminEventoEntradas: (id: string) => `/admin/eventos/${id}/entradas`,
  adminEventoVentas: (id: string) => `/admin/eventos/${id}/ventas`,
  adminEventoKiosco: (id: string) => `/admin/eventos/${id}/kiosco`,
  adminComunidad: "/admin/comunidad",
  adminProductos: "/admin/productos",
  adminVentas: "/admin/ventas",
  adminCaja: "/admin/caja",
  adminCajero: "/admin/cajero",
  adminPuerta: "/admin/puerta",
  adminUsuarios: "/admin/usuarios",
} as const;

export const PUBLIC_NAV_LINKS = [
  { href: ROUTES.home, label: "Inicio" },
  { href: ROUTES.eventos, label: "Eventos" },
  { href: ROUTES.comunidad, label: "Comunidad" },
  { href: ROUTES.sobre, label: "Sobre Australe" },
  { href: ROUTES.contacto, label: "Contacto" },
] as const;

export const ADMIN_NAV_LINKS = [
  { href: ROUTES.admin, label: "Inicio" },
  { href: ROUTES.adminEventos, label: "Eventos" },
  { href: ROUTES.adminComunidad, label: "Comunidad" },
  { href: ROUTES.adminProductos, label: "Productos" },
  { href: ROUTES.adminVentas, label: "Ventas" },
  { href: ROUTES.adminCaja, label: "Caja" },
  { href: ROUTES.adminCajero, label: "Cajero" },
  { href: ROUTES.adminPuerta, label: "Puerta" },
  { href: ROUTES.adminUsuarios, label: "Usuarios" },
] as const;
